server {
    listen 443 ssl;
    server_name repo.lab.internal;

    ssl_certificate     /etc/nginx/certs/lab.internal.crt;
    ssl_certificate_key /etc/nginx/certs/lab.internal.key;

    client_max_body_size 0;

    # Docker registry
    location /v2/ {
        proxy_pass http://192.168.100.203:5000;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;

        proxy_request_buffering off;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://192.168.100.203:8081;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}