---
- name: Configure NGINX Reverse Proxy Server
  hosts: reverse-proxy
  become: true
  roles:
    - reverse-proxy

- name: Configure MariaDB Server
  hosts: mariadb
  roles:
    - mariadb

- name: Configure Nexus Server
  hosts: nexus
  roles:
    - nexus

- name: Configure Kubernetes Control Plane
  hosts: k8s-control-plane
  become: true
  roles:
    - k8s-control-plane

- name: Configure Kubernetes Worker Nodes
  hosts: k8s-worker-nodes
  become: true
  roles:
    - k8s-worker-nodes