---
- name: Configure NGINX Reverse Proxy Server
  hosts: reverse-proxy
  become: true
  roles:
    - reverse-proxy

- name: Configure MariaDB Server
  hosts: mariadb
  roles:
    - mariadb

- name: Configure Nexus Server
  hosts: nexus
  roles:
    - nexus